require_relative 'lib/emoji_finder'
require_relative 'lib/gifmaker'
require_relative 'lib/progress'
require_relative 'lib/image_scanner'
require_relative 'lib/image_generator'

require 'pathname'
require 'pry'
require 'Rmagick'
require 'json'